<h1> Análise dados portal da transparência

![](https://www.asaas.com/blog/wp-content/uploads/2016/02/brasil_-_reproducao.jpg)

In [117]:
import pandas as pd

In [118]:
df = pd.read_csv('ceaps_dataset.csv', skiprows=1, delimiter=';',encoding='latin1')
df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO
0,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,13/01/2016,Despesa com pagamento de energia elétrica para...,"73,6"
1,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,18/01/2016,Pagamento de energia elétrica para o escritóri...,"206,84"
2,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/16,04/01/2016,"Despesa com pagamento de aluguel, utilizado pa...",6000
3,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.423.963/0001-11,OI MÓVEL S.A.,661639001,16/01/2016,despesa com pagamento de telefonia para o escr...,"407,48"
4,2016,1,ACIR GURGACZ,Aquisição de material de consumo para uso no e...,62.652.961/0001-38,AGÊNCIA ESTADO S.A.,00608918,06/01/2016,Aquisição de publicação virtual de conteúdo jo...,550

In [119]:
df.describe()

           ANO           MES
count  26691.0  26691.000000
mean    2016.0      6.470908
std        0.0      3.257134
min     2016.0      1.000000
25%     2016.0      4.000000
50%     2016.0      6.000000
75%     2016.0      9.000000
max     2016.0     12.000000

In [120]:
df['VALOR_REEMBOLSADO'] = df['VALOR_REEMBOLSADO'].str.replace(',','.')
df['VALOR_REEMBOLSADO'] = pd.to_numeric(df['VALOR_REEMBOLSADO'])

In [121]:
df['DATA'] = df['DATA'].str.replace('20/07/5017','20/07/2017') 
df['DATA'] = df['DATA'].str.replace('02/04/3016','02/04/2016')
df['DATA'] = df['DATA'].str.replace('04/04/216','04/04/2016')

In [122]:
df['DATA'] = pd.to_datetime(df['DATA'], errors='coerce')

In [123]:
df.dropna(subset=['DATA'], inplace=True)

In [124]:
df['DIA'] = df['DATA'].dt.day
df['ANO'] = df['DATA'].dt.year

In [125]:
mapper = {'Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.':'Aluguel',
          'Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. ':'Aquisição de material',
          'Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar':'Consultoria',
          'Locomoção, hospedagem, alimentação, combustíveis e lubrificantes' : 'Logística',
          'Passagens aéreas, aquáticas e terrestres nacionais' : 'Passagem',
          'Divulgação da atividade parlamentar' : 'Divulgações',
          'Serviços de Segurança Privada':'Segutança'}
df['TIPO_DESPESA'] = df['TIPO_DESPESA'].map(mapper)

In [126]:
df[df['TIPO_DESPESA'].isnull()]

Empty DataFrame
Columns: [ANO, MES, SENADOR, TIPO_DESPESA, CNPJ_CPF, FORNECEDOR, DOCUMENTO, DATA, DETALHAMENTO, VALOR_REEMBOLSADO, DIA]
Index: []

In [127]:
df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,DIA
0,2016,1,ACIR GURGACZ,Aluguel,05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,2016-01-13,Despesa com pagamento de energia elétrica para...,73.60,13
1,2016,1,ACIR GURGACZ,Aluguel,05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,2016-01-18,Pagamento de energia elétrica para o escritóri...,206.84,18
2,2016,1,ACIR GURGACZ,Aluguel,004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/16,2016-04-01,"Despesa com pagamento de aluguel, utilizado pa...",6000.00,1
3,2016,1,ACIR GURGACZ,Aluguel,05.423.963/0001-11,OI MÓVEL S.A.,661639001,2016-01-16,despesa com pagamento de telefonia para o escr...,407.48,16
4,2016,1,ACIR GURGACZ,Aquisição de material,62.652.961/0001-38,AGÊNCIA ESTADO S.A.,00608918,2016-06-01,Aquisição de publicação virtual de conteúdo jo...,550.00,1

In [128]:
df.to_csv('dados_limpos.csv', encoding='latin1',index=False)